@host=http://localhost:5015
@adminId=4201345D-51E4-466F-9740-F52C890CAB93

POST {{host}}/api/Subscription
Content-Type: application/json

{
    "SubscriptionType": "Starter",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }