@host=http://localhost:5015
@adminId=2150E333-8FDC-42A3-9474-1A3956D46DE8

POST {{host}}/api/Subscription
Content-Type: application/json

{
    "SubscriptionType": "P",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }