@host=http://localhost:5015
@subscriptionId=5fded736-719c-423d-a068-04c048dab62b
@gymId=730c30d4-1cb3-4370-80f7-ee23125ed4eb

POST {{host}}/api/Subscription/{{subscriptionId}}/Gyms/{{gymId}}/Trainer
Content-Type: application/json

{
    "trainerId": "3AB4C726-51EA-4E47-B189-14FD7C5A96A8"
}